export default {
      Cards: [
            {
                  rape: "Antonio Fuentes Jara",
                  id: 1,
                  title: "Con factura",
                  Eta: "07/12/2024",
                  tipo: "Historial",
                  prioridad: "1",
                  progreso: "todo",
            },
            {
                  rape: "Joao",
                  id: 2,
                  title: "Card Title",
                  Eta: "12/10/2022",
                  tipo: "Historial",
                  prioridad: "3",
                  progreso: "todo",
            }, {
                  rape: "Joao",
                  id: 3,
                  title: "Proyect Title",
                  Eta: "12/10/2022",
                  tipo: "Historial",
                  prioridad: "3",
                  progreso: "todo",
            },
            {
                  rape: "Joao",
                  id: 4,
                  title: "Card Title",
                  Eta: "12/10/2022",
                  tipo: "Historial",
                  prioridad: "3",
                  progreso: "todo",
            },
            {
                  rape: "Joao",
                  id: 5,
                  title: "Card Title",
                  Eta: "12/10/2022",
                  tipo: "Historial",
                  prioridad: "3",
                  progreso: "todo",
            },
            {
                  rape: "Joao",
                  id: 6,
                  title: "Proyect Title",
                  Eta: "12/10/2022",
                  tipo: "Historial",
                  prioridad: "1",
                  progreso: "todo",
            },
            {
                  rape: "Antonio",
                  id: 7,
                  title: "Card Title",
                  Eta: "12/10/2022",
                  tipo: "Historial",
                  prioridad: "2",
                  progreso: "inprogress",
            },
            {
                  rape: "Antonio",
                  id: 8,
                  title: "Proyect Title",
                  Eta: "12/10/2022",
                  tipo: "Historial",
                  prioridad: "2",
                  progreso: "inprogress",
            },

            {
                  rape: "Cesar",
                  id: 9,
                  title: "Proyect Title",
                  Eta: "12/10/2022",
                  tipo: "Historial",
                  prioridad: "3",
                  progreso: "inprogress",
            },
            {
                  rape: "Camilo",
                  id: 10,
                  title: "Proyect Title",
                  Eta: "12/10/2022",
                  tipo: "Historial",
                  prioridad: "1",
                  progreso: "inprogress",
            },
            {
                  rape: "Carlos Torres",
                  id: 11,
                  title: "Titulo de Proyecto",
                  Eta: "",
                  tipo: "Historial",
                  prioridad: "1",
                  progreso: "todo",
            },
            {
                  rape: "Alex",
                  id: 12,
                  title: "Proyect Title",
                  Eta: "12/10/2022",
                  tipo: "Historial",
                  prioridad: "2",
                  progreso: "done",
            }, {
                  rape: "hola",
                  id: 15,
                  title: "Proyect Title",
                  Eta: "12/10/2022",
                  tipo: "Historial",
                  prioridad: "1",
                  progreso: "done",
            },
            {
                  rape: "Nayeli",
                  id: 13,
                  title: "Proyect Title",
                  Eta: "12/10/2022",
                  tipo: "Historial",
                  prioridad: "2",
                  progreso: "done",
            },


      ]
};